# Generated by Django 5.1 on 2024-12-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_data',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='contact_data',
            old_name='message',
            new_name='user_message',
        ),
        migrations.RenameField(
            model_name='contact_data',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='contact_data',
            old_name='phone',
            new_name='user_phone',
        ),
    ]
