# Generated by Django 5.1 on 2024-12-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_rename_email_contact_data_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_data',
            new_name='contact_datas',
        ),
    ]
