# Generated by Django 5.1 on 2024-12-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_rename_contact_data_contact_datas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_datas',
            new_name='contact_data',
        ),
    ]
