# Generated by Django 5.1 on 2024-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_img', models.FileField(default=None, max_length=50, null=True, upload_to='')),
                ('skill_name', models.CharField(max_length=10)),
            ],
        ),
    ]
